server:
  port: 8080

# Application logging
logging:
  level:
    root: WARN
    org.springframework: INFO
    com.mulecode: DEBUG

spring:
  application:
    name: kafka-sample


#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: myGroup

